//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace ShapesProject {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class XmlShapesContainer {
        
        private string ellipsesField;
        
        private XmlShapesContainerCirclesCircle[] circlesField;
        
        private XmlShapesContainerNonCirclesNonCircle[] nonCirclesField;
        
        private XmlShapesContainerRectangles[] rectanglesField;
        
        private XmlShapesContainerTriangles[] trianglesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ellipses {
            get {
                return this.ellipsesField;
            }
            set {
                this.ellipsesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Circle", typeof(XmlShapesContainerCirclesCircle), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public XmlShapesContainerCirclesCircle[] Circles {
            get {
                return this.circlesField;
            }
            set {
                this.circlesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("NonCircle", typeof(XmlShapesContainerNonCirclesNonCircle), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public XmlShapesContainerNonCirclesNonCircle[] NonCircles {
            get {
                return this.nonCirclesField;
            }
            set {
                this.nonCirclesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rectangles", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public XmlShapesContainerRectangles[] Rectangles {
            get {
                return this.rectanglesField;
            }
            set {
                this.rectanglesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Triangles", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public XmlShapesContainerTriangles[] Triangles {
            get {
                return this.trianglesField;
            }
            set {
                this.trianglesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class XmlShapesContainerCirclesCircle {
        
        private string radiusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Radius {
            get {
                return this.radiusField;
            }
            set {
                this.radiusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class XmlShapesContainerNonCirclesNonCircle {
        
        private string radius1Field;
        
        private string radius2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Radius1 {
            get {
                return this.radius1Field;
            }
            set {
                this.radius1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Radius2 {
            get {
                return this.radius2Field;
            }
            set {
                this.radius2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class XmlShapesContainerRectangles {
        
        private XmlShapesContainerRectanglesSquaresSquare[] squaresField;
        
        private XmlShapesContainerRectanglesNonSquaresRectangle[] nonSquaresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Square", typeof(XmlShapesContainerRectanglesSquaresSquare), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public XmlShapesContainerRectanglesSquaresSquare[] Squares {
            get {
                return this.squaresField;
            }
            set {
                this.squaresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Rectangle", typeof(XmlShapesContainerRectanglesNonSquaresRectangle), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public XmlShapesContainerRectanglesNonSquaresRectangle[] NonSquares {
            get {
                return this.nonSquaresField;
            }
            set {
                this.nonSquaresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class XmlShapesContainerRectanglesSquaresSquare {
        
        private string sideField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Side {
            get {
                return this.sideField;
            }
            set {
                this.sideField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class XmlShapesContainerRectanglesNonSquaresRectangle {
        
        private string length1Field;
        
        private string length2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Length1 {
            get {
                return this.length1Field;
            }
            set {
                this.length1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Length2 {
            get {
                return this.length2Field;
            }
            set {
                this.length2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class XmlShapesContainerTriangles {
        
        private XmlShapesContainerTrianglesScalenesScalene[] scalenesField;
        
        private XmlShapesContainerTrianglesIsoscelesIsoscele[] isoscelesField;
        
        private XmlShapesContainerTrianglesEquilateralsEquilateral[] equilateralsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Scalene", typeof(XmlShapesContainerTrianglesScalenesScalene), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public XmlShapesContainerTrianglesScalenesScalene[] Scalenes {
            get {
                return this.scalenesField;
            }
            set {
                this.scalenesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Isoscele", typeof(XmlShapesContainerTrianglesIsoscelesIsoscele), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public XmlShapesContainerTrianglesIsoscelesIsoscele[] Isosceles {
            get {
                return this.isoscelesField;
            }
            set {
                this.isoscelesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Equilateral", typeof(XmlShapesContainerTrianglesEquilateralsEquilateral), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public XmlShapesContainerTrianglesEquilateralsEquilateral[] Equilaterals {
            get {
                return this.equilateralsField;
            }
            set {
                this.equilateralsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class XmlShapesContainerTrianglesScalenesScalene {
        
        private string side1Field;
        
        private string side2Field;
        
        private string side3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Side1 {
            get {
                return this.side1Field;
            }
            set {
                this.side1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Side2 {
            get {
                return this.side2Field;
            }
            set {
                this.side2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Side3 {
            get {
                return this.side3Field;
            }
            set {
                this.side3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class XmlShapesContainerTrianglesIsoscelesIsoscele {
        
        private string side1Field;
        
        private string otherSidesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Side1 {
            get {
                return this.side1Field;
            }
            set {
                this.side1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OtherSides {
            get {
                return this.otherSidesField;
            }
            set {
                this.otherSidesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class XmlShapesContainerTrianglesEquilateralsEquilateral {
        
        private string sideField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Side {
            get {
                return this.sideField;
            }
            set {
                this.sideField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class NewDataSet {
        
        private XmlShapesContainer[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("XmlShapesContainer")]
        public XmlShapesContainer[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
}
